"""Модуль с константами приложения quiz"""

CATEGORY_TITLE_MAX_LENGTH = 100
QUIZ_TITLE_MAX_LENGTH = 200
DESCRIPTION_MAX_LENGTH = 500
QUESTION_TEXT_MAX_LENGTH = 500
CORRECT_ANSWER_MAX_LENGTH = 500
EXPLANATION_MAX_LENGTH = 250
DIFFICULTY_MAX_LENGTH = 10
MIN_OPTIONS_COUNT = 2
