# Generated by Django 5.2.6 on 2026-09-29 15:06

import django.db.models.deletion
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название квиза')),
                (
                    'description',
                    models.CharField(blank=True, default='', max_length=500, verbose_name='Описание квиза'),
                ),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                (
                    'description',
                    models.CharField(blank=True, default='', max_length=500, verbose_name='Описание вопроса'),
                ),
                (
                    'options',
                    models.JSONField(validators=[quiz.models.validate_options], verbose_name='Варианты ответа'),
                ),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Правильный ответ')),
                (
                    'explanation',
                    models.CharField(blank=True, default='', max_length=250, verbose_name='Объяснение ответа'),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')],
                        max_length=10,
                        verbose_name='Сложность',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='quiz.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'quiz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='quiz.quiz',
                        verbose_name='Квиз',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
